config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#home"
  get "about", to: "welcome#about"

  get "signup", to: "users#new"
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"

  delete 'logout', to: 'sessions#destroy'
  
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    
    has_many :article_categories
    has_many :categories , through: :article_categories
    
    validates :title, presence: true, length: { minimum:3, maximum:50}
    validates :description, presence: true, length: { minimum:10, maximum:300}
    validates :user_id, presence: true


    # iuiuiuiui
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    @article.user = current_user 

    respond_to do |format|
      if @article.save
        format.html { redirect_to user_path(current_user), notice: "Article was successfully created." }
        #format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to user_path(current_user), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :user_id, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user  and !current_user.admin?
          redirect_to root_path, notice: "You can only editing or delete your own articles"
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="container py-4">

  <div class="list"> 

    <% obj.each do |article| %>
      <div class="card mb-3">
        <div class="card-header d-flex justify-content-between align-items-center">  
          <h5 class="m-0">
            <%= link_to article_path(article.id), class:"text-decoration-none" do %>
              Title: <%= article.title %> 
            <% end %>
          </h5>
          <div class="d-flex">
            <% if logged_in? && (current_user == article.user || current_user.admin?)%>
              <%= link_to 'Edit', edit_article_path(article), class:"btn btn-warning mx-2 opacity-75"  %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger opacity-75"  %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title fw-normal">Description</h5>
          <p class="card-text fw-light"><%= article.description %></p>

          
          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %> </p>
          <% end %>
          
          <div class="text-end fw-lighter">
            <%= article.updated_at.strftime("%F %H:%M")  %>
          </div>
        </div>
      </div>
    <% end %>

    <% if obj.length == 0 %>
      <p class="text-center">0 Articles</p>
    <% end %>

  </div>
  </div>
</div>

app/views/articles/_form.html.erb
<% if article.errors.any? %>

  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: article, local: true, :html => {class:"form-horizontal", role: "form"}) do |form| %>
   <div class="mb-3 row">
    <%= form.label :title, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class:"form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :description, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :description, rows: 10,class:"form-control" %>
    </div>
  </div>

  <div class="mb-3 row d-flex align-items-center">
    <%= form.label "Category", class:"col-sm-2 col-form-label" %>

    <div class="col-sm-10">
      <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class:"checkbox-inline input_checkbox me-3"){cb.check_box(class: "checkbox me-1") + cb.text}  %>
      <% end %>
    </div>
  </div>

  <div class="actions d-flex justify-content-between align-items-center my-3">
    <%= form.submit class:"btn btn-primary " %>
    <%= link_to 'Cancel', articles_path, class:"btn btn-light" %>
  </div>

  <div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container py-4">
    <div class="d-flex justify-content-between mb-3 align-items-center">
        <h3 class="">Editing Article</h3>
        <%= link_to 'Show', @article %> 
    </div>

    <%= render 'form', article: @article %>

</div>

app/views/articles/index.html.erb
<div class="container py-4">
  <div class="d-flex justify-content-between">
    <h3 class="mb-3 text-center">All Articles</h3>
  </div>

  <div class=""> 

    <%= will_paginate @articles, class: "w-100 Page navigation d-flex justify-content-center"%>

    <% @articles.each do |article| %>
      <div class="card my-3">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="m-0">
            <%= link_to article_path(article.id), class:"text-decoration-none", title:"Show article" do %>
              Title: <%= article.title %> 
            <% end %>
          </h5>
          <div>
            <% if logged_in? && (current_user == article.user || current_user.admin?)%>
              <%= link_to 'Edit', edit_article_path(article), class:"btn btn-warning me-2 px-2 py-1 opacity-75", title:"Edit article"  %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger px-2 py-1 opacity-75", title:"Delete article"  %>
            <% end %>
          </div>
        </div>


        <div class="card-body">
          <h5 class="card-title fw-normal">Description</h5>
          <p class="card-text fw-light mb-2"><%= article.description %></p>
          
          <div class="d-flex justify-content-between">
            <div class="d-flex  mt-2">
             <% if article.categories.any?  %>
              <p class="m-0">
                Categories: <%= render article.categories %> 
              </p>
             <% end %>
            </div>
          
            <div class="text-end fw-lighter">
                <%= article.updated_at.strftime("%F %H:%M")  %>
            </div>
          </div>
          <p class="text-end fw-light mb-2">By: <%= article.user.username %></p>

        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container py-4">
    <h3 class="mb-3">New Article</h3>

    <%= render 'form', article: @article %>

</div>

app/views/articles/show.html.erb
<div class="container py-5"> 
  <div class="card mb-3">
    <div class="card-header d-flex justify-content-between">
      <h5 class="">Title: <%= @article.title %> </h5>
      <div class="d-flex">
          <% if logged_in? && (current_user == @article.user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-warning px-5 py-1 opacity-75", title:"Edit article" %> 
          <% end %>
      </div>
    </div>
    <div class="card-body">
        <div class="row mb-3">
          <label for="", class="col-sm-4 fw-bold">
            Description:
          </label>
          <div class="col-sm-8">
            <%= @article.description %>
          </div>
        </div>
        <% if @article.categories.any? %>
          <p>Categories: <%= render @article.categories %> </p>
        <% end %>
        <div class="d-flex justify-content-end mt-2">        
          <%= link_to 'Back', articles_path, class:"btn btn-light px-5" %>
        </div>
      </div>
 
    </div>
  </div>
  