config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#home"
  get "about", to: "welcome#about"

  get "signup", to: "users#new"
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"

  delete 'logout', to: 'sessions#destroy'
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 25}
  validates :password, presence: true, length: {minimum: 6, maximum: 120}
  validates :email, presence: true, uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

  # GET /users or /users.json
  def index
    @users = User.all.paginate(page: params[:page], per_page: 2)
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :email)
    end

    def require_same_user
      if current_user != @user 
          redirect_to root_path, notice: "You can only edit your own account"
      end
    end
    def require_admin
      if logged_in? and !current_user.admin?
          redirect_to root_path, notice: "Only admin users can perform that action"
      end
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: user, local: true,  :html => {class:"form-horizontal", role: "form"}) do |form| %>

  <div class="mb-3 row">
    <%= form.label :username, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :username, class:"form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :password, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.password_field :password, class:"form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :password_confirmation, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.password_field :password_confirmation, class:"form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :email, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.email_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="actions d-flex justify-content-between align-items-center my-4">
    <%= form.submit(user.new_record? ? "Sign up" : "Update account",class:"btn btn-primary") %>
    <%= link_to 'Cancel', users_path, class:"btn btn-light" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="container py-5"> 
    <div class="d-flex justify-content-between">
        <h3 class="mb-3 text-center">Edit your account</h3>
        <%= link_to 'Show', @user %>
    </div>

    <%= render 'form', user: @user %>

</div>

app/views/users/index.html.erb
<div class="container py-4"> 
  <div class="d-flex justify-content-between mb-3">
    <h3>Users</h3>
    <!--<%= link_to 'New User', new_user_path, class:"btn btn-success" %>-->
  </div>
  <div class="">
    <%= will_paginate @users, class: "w-100 Page navigation d-flex justify-content-center"%>

    <% @users.each do |user| %>
        <div class="card shadow w-100 my-3">
          <div class="card-body text-center d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
              <%= gravatar_for user %>
              <%= link_to user_path(user.id), class:"text-decoration-none link-dark text-dark ms-3 fw-bold", title:"Show page" do %>
                Username: <%= user.username %> 
              <% end %>
            </div>

            <h5 class="card-title fw-normal m-0">Articles: <%= user.articles.count  %>
            </h5>

            <% if logged_in? && current_user.admin?%>
              <!--<td><%= link_to 'Edit', edit_user_path(user) %></td>-->
              <%= link_to 'Destroy', user,class:"btn btn-danger opacity-75", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>

          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container py-5"> 
    <h3 class="text-center mb-3">Signup - Alpha Blog</h3>

    <%= render 'form', user: @user %>

</div>

app/views/users/show.html.erb
<div class="container py-5"> 
  <div class="mb-3 mx-auto">
    <div class=" d-flex flex-column align-items-center py-3"> 
      <div class=" ms-3">
        <h3 class="mb-2">Welcome to <%= @user.username %>'s page </h3>
      </div>
      <%= gravatar_for @user %>
    </div>

    <div class="">
      <div class="d-flex justify-content-between">
        <h4 class="px-3 my-2">Articles the <%= @user.username %></h4>
        <%= link_to 'New Article', new_article_path, class:"btn btn-primary d-flex align-items-center" %>
      </div>
        
        <%= will_paginate @user_articles, class: "w-100 Page navigation d-flex justify-content-center" %>

        <%= render 'articles/article', obj: @user_articles %>

        <!--<div class="d-flex justify-content-between mb-3 px-3">
          <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-success px-5" %> 
          <%= link_to 'Back', users_path, class:"btn btn-light px-5" %>
        </div>-->
    </div>
  </div>
</div>