config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#home"
  get "about", to: "welcome#about"

  get "signup", to: "users#new"
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"

  delete 'logout', to: 'sessions#destroy'
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles , through: :article_categories
    

    validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :require_login_admin, except: [:index, :show]


  # GET /categories or /categories.json
  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 4)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    def require_login_admin
      unless logged_in? and current_user.admin? 
          redirect_to root_path, notice: "You don't have permissions for this action."
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span class="badge bg-info text-dark me-2">
  <%= link_to category.name, category_path(category), class:"text-decoration-none text-dark px-2 py-2" %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container py-4">
  <div class="d-flex justify-content-between">
    <h5 class="my-0">Categories</h5>
    <% if logged_in? and current_user.admin? %>
      <%= link_to 'New Category', new_category_path, class:"d-flex align-items-center btn btn-success" %>
    <% end %>
  </div>

  <div>
    <%= will_paginate @categories, class: "w-100 Page navigation d-flex justify-content-center"%>

    <% @categories.each do |category| %>
      <div class="card my-2">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <p class="m-0">
              <%= link_to category.name.upcase, category, class:"text-decoration-none", title:"Show category #{category.name}" %>
            </p>
            <p class="text-dark m-0"> Articles: <%= category.articles.count %> </p>
          </div>
          <div class="d-flex justify-content-end">
            <% if logged_in? and current_user.admin? %>
              <%= link_to 'Edit', edit_category_path(category), class:"btn btn-warning me-2" %>
              <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container"> 

    <div class="d-flex justify-content-between">
      <h5>
        <%= "Category: " + @category.name   %>
      </h5>
      <% if logged_in? and current_user.admin? %>
        <%= link_to 'Edit', edit_category_path(@category), class:"btn btn-warning" %> 
      <% end %>
    </div>

    <div class="py-3">
      <%= will_paginate @category_articles, class: "w-100 Page navigation d-flex justify-content-center" %>

      <%= render 'articles/article', obj: @category_articles %>
    </div>
</div>