config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#home"
  get "about", to: "welcome#about"

  get "signup", to: "users#new"
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"

  delete 'logout', to: 'sessions#destroy'
  
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark">
  <div class="container py-3 text-white">
    <p class="text-center m-0 p-0">Copyright © 2021</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="messages py-3">
  <div class="container"> 
    <div class="col-xs-10 col-xs-offset-1">
      <% if notice != nil %>
        <div id="" class="alert alert-success">
          <div class="d-flex justify-content-between">
            <%= notice %>
            <a href="#" class="close" data-disimiss="alert">&#215;</a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="py-4 px-3 navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container-fluid">
    <%= link_to root_path, class:"navbar-brand me-3 bg-black text-white px-2 rounded fw-bold" do %>
      Alpha Blog
    <% end %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!--<li class="nav-item">
            <%= link_to "About", about_path, class:"nav-link"%>
        </li>-->
        <li class="nav-item">
            <%= link_to "Articles", articles_path, class:"nav-link"%>
        </li>
         <li class="nav-item">
            <%= link_to "Usuarios", users_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories 
          </a>
          <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
            <li>
              <%= link_to "All", categories_path, class:"dropdown-item" %>
            </li>
            <% Category.all.each do |item| %>
              <li>
                <%= link_to "#{item.name}", category_path(item.id), class:"dropdown-item" %>
              </li>
            <% end %>
            <li>
              <% if logged_in? and current_user.admin? %>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <%= link_to "New category", new_category_path, class:"dropdown-item" %>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <% if logged_in?  %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile <%= current_user.username %> <%= current_user.admin? ? ' - Admin': '' %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
           
            <li>
              <%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %>
            </li>
            <li>
              <%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <%= render 'layouts/messages' %>  
      <%= yield %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>